import sys
import os

# Add parent directory to path so we can import core
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from core.ppt_renderer import PPTRenderer

def generate_sample():
    print("Generating sample PPT from hardcoded data...")
    
    renderer = PPTRenderer()
    
    # Title Slide
    renderer.add_title_slide("Sample Presentation", "Generated by Auto PPT Generator")
    
    # Slide 1
    renderer.add_content_slide(
        "Introduction", 
        [
            "This is a sample presentation.",
            "It was generated without using an LLM.",
            "It demonstrates the layout and structure."
        ],
        notes="Speaker notes would go here."
    )
    
    # Slide 2
    renderer.add_content_slide(
        "Features",
        [
            "Automated content generation",
            "Support for OpenAI, Anthropic, and Google",
            "Clean minimalist design"
        ]
    )
    
    # Citations
    renderer.add_citations_slide([
        "https://example.com/source1",
        "https://example.com/source2"
    ])
    
    output_path = "samples/sample.pptx"
    renderer.save(output_path)
    print(f"Sample saved to {output_path}")

if __name__ == "__main__":
    generate_sample()
